### ISSUE TITLE
样式完全错乱

### ISSUE THREAD

**Issue by chenwangji** [zkboys/react-admin#1]
很喜欢这个项目，但是我这边出了点问题，不知道怎么回事。
git clone 项目下来，然后安装依赖正常，启动正常，页面也没报错，但是样式却错乱了。
![1550339600](https://user-images.githubusercontent.com/23144765/52903364-60421d80-3257-11e9-84ff-32e3d635c1a2.png)
![1550339865](https://user-images.githubusercontent.com/23144765/52903371-7ea81900-3257-11e9-92d3-46b93fd7845f.png)

**Comment by zkboys** [comment]
非常感谢您对此项目的支持，但是您的问题，我并不能重新。先排查一下是不是样式没有引入进去。
![image](https://user-images.githubusercontent.com/11864780/52907616-e5512500-329f-11e9-90ff-611879af987d.png)

**Comment by chenwangji** [comment]
样式文件确实没引进来，不过不太熟悉代码，不知道如何更改。。。
![1550378003](https://user-images.githubusercontent.com/23144765/52908403-6dd7c180-32b0-11e9-9cc4-c11961fdeff8.png)
你自己重新 clone 下来之后没遇到这个问题吗？
另外能否发布一个预览地址，这样就算本地起不来，也能看看效果，方便学习。

**Comment by zkboys** [comment]
加一下QQ群 667271903 然后我们一起看一下这个问题

**Comment by chenwangji** [comment]
ok, 麻烦通过下

**Comment by zkboys** [comment]
css-loader生成hash跨平台兼容性问题，已解决~
