### ISSUE TITLE
安装的时候报错

### ISSUE THREAD

**Issue by sillyfeng** [zkboys/react-admin#3]
node `11.10`    npm `6.7.0`
在安装的时候报错： 
`npm ERR! path D:\react-admin\react-admin-master\node_modules\highlight.js\tools\build.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'D:\react-admin\react-admin-master\node_modules\highlight.js\tools\build.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
`

**Comment by zkboys** [comment]
使用yarn安装试试

**Comment by sillyfeng** [comment]
yarn没有试过，只能等回家试。公司是内网，只有cnpm私服，没有yarn的条件。
