### ISSUE TITLE
关于 styleName 热更新

### ISSUE THREAD

**Issue by whateveryoudo** [zkboys/react-admin#4]
大神请教,添加一个 styleName，会报错 name不存在（实际在对应的styles里面添加了相关类名）,但是先在less写,再添加styleName就正确。。。

**Comment by zkboys** [comment]
会有这个问题，写了less之后，jsx文件并不会重新编译，还是会找不到，手动修改一下jsx，触发一下编译就行了。等我空我看看有什么好的方法

**Comment by whateveryoudo** [comment]
是在 jsx里面先写了一个  styleName,就报错了,就算我在 less文件中加了 也没用,  但是我先在 less里面写了，再在jsx里面写就不会报错..   (你说反了!)

**Comment by zkboys** [comment]
我的意思是，你再去less文件补充，jsx不会编译，自然找不到，补充之后修改jsx重新编译就好了
