### ISSUE TITLE
设置头部加左侧导航后无法点击用户头像下拉的设置

### ISSUE THREAD

**Issue by viewhang** [zkboys/react-admin#5]
面包屑占用空间太大，而且设置头部加左侧导航后无法点击用户头像下拉的设置，会被面包屑遮住

**Comment by zkboys** [comment]
没太明白，有截图吗？

**Comment by viewhang** [comment]
![image](https://user-images.githubusercontent.com/26957298/55707867-36b3a000-5a17-11e9-8e38-36dee9fdce61.png)

**Comment by zkboys** [comment]
是个问题，已经修复，在src/layouts目录下，找到 .page-head-fixed 这个css样式，将里面的z-index修改为998即可。
