### ISSUE TITLE
?.的写法

### ISSUE THREAD

**Issue by whateveryoudo** [zkboys/react-admin#6]
请教下 ?. 表达式写法, 转为平时的写法是什么样子？ 配置支持此语法是在什么地方额？

**Comment by zkboys** [comment]
这个是ES的一个新语法，叫做proposal-optional-chaining，需要babel7支持，具体可参见：[https://github.com/tc39/proposal-optional-chaining](https://github.com/tc39/proposal-optional-chaining)。获取嵌套比较深的对象属性，判断起来很方便。
